name: CI

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check for fdescribe() and fit() in test files
      run: |
        FDESCRIBE=$(find ./app/specs -type f -exec grep "fdescribe(" {} \;)
        FIT=$(find ./app/specs -type f -exec grep "fit(" {} \;)
        if [ -n "$FDESCRIBE" ]; then
          echo "fdescribe found"
          echo "$FDESCRIBE"
          exit 1
        fi
        if [ -n "$FIT" ]; then
            echo "fit found"
            echo "$FIT"
            exit 1
        fi
        
    - name: Run unit tests
      run: |
        sudo apt-get install yarn
        cd app
        yarn install
        yarn jest